project:
  type: website
  output-dir: docs

website:
  title: "GW Nashman Center Open Education Resources"
  navbar:
    left:
      - text: "Home"
        file: src/pages/index.qmd
      - text: "About"
        file: src/pages/about.qmd
      - text: "Dashboard"
        file: src/pages/dashboard.qmd
      - text: "Contact"
        file: src/pages/contact.qmd

format:
  html:
    theme:
      light: default
    scss: src/custom.scss
    include-in-header: src/includes/header.html
